[package]
name = "rust_samples"
version = "0.1.0"
edition = "2018"

[workspace]
members =["rust_lang",
    "async-chat",
    "hello_macro_derive", "hello_macro",
    "nacos-client", "nacos-common", "nacos-config-derive"]


[dependencies]
actix-web = "4.0.0-beta.13"