[package]
name = "nacos-client"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
reqwest = "0.11.4"
tokio = { version = "1.11.0", features = ["full"] }
